spring:
  application:
    name: authproject

  datasource:
    url: jdbc:postgresql://localhost:5432/authprojectdb
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

authproject:
  security:
    jwt:
      secret: "O77K/FnMAjtMqR293mltcrqBPdRTF+1UwBd2RJiu4SjccmPnMPwt+NsUTe1k+4YU2XEDXeoCwbojcN31zVX8Sw=="